# Generated by Django 6.0.3 on 2026-03-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeaknessTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_name', models.CharField(max_length=100)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('last_occurrence', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('total_mistakes', models.PositiveIntegerField(default=0)),
                ('top_weaknesses', models.JSONField(default=list)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
    ]
