# Generated by Django 6.0.3 on 2026-03-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerprofile',
            name='daily_streak',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='proficiency_level',
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='source_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ar', 'Arabic'), ('es', 'Spanish')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='target_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ar', 'Arabic'), ('es', 'Spanish'), ('it', 'Italian'), ('de', 'German')], default='en', max_length=10),
        ),
    ]
