# Generated by Django 6.0.3 on 2026-03-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_file', models.FileField(upload_to='submissions/audio/%Y/%m/%d/')),
                ('recorded_at', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('retrying', 'Retrying'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='curriculum.question')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
