# Generated by Django 6.0.3 on 2026-03-13 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_exercise_feedback'),
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysubmission',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='curriculum.question'),
        ),
    ]
