# Generated by Django 6.0.3 on 2026-03-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_text', models.TextField()),
                ('correction', models.TextField()),
                ('explanation', models.TextField()),
                ('category', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('pronunciation', 'Pronunciation'), ('tone', 'Tone')], max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_transcript', models.TextField(blank=True)),
                ('rewritten_version', models.TextField(blank=True, help_text='Higher-level rewrite of the transcript')),
                ('general_feedback', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'submission analyses',
            },
        ),
    ]
