# Generated by Django 6.0.3 on 2026-03-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionanalysis',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='submissions.dailysubmission'),
        ),
        migrations.AddField(
            model_name='mistake',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='analysis.submissionanalysis'),
        ),
    ]
