# Generated by Django 6.0.3 on 2026-03-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistake',
            name='category',
            field=models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('pronunciation', 'Pronunciation'), ('tone', 'Tone'), ('style', 'Style')], max_length=20),
        ),
    ]
