# Generated by Django 6.0.3 on 2026-03-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='due_date',
        ),
    ]
