# Generated by Django 6.0.3 on 2026-03-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_remove_exercise_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='user_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weakness_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
