# Generated by Django 6.0.3 on 2026-03-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_rework_exercise_link_to_mistake'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
